name: Publish Latest Version

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-latest-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Extract Syncplay Version from Dockerfile
        id: get-version
        run: |
          syncplay_version=$(grep -oP '(?<=ENV SYNCPLAY=")[^"]+' Dockerfile)
          echo "syncplay_version=${syncplay_version}"
          echo "syncplay_version=${syncplay_version}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          tags: |
            ${{ vars.DOCKER_IMAGE }}:v${{ steps.get-version.outputs.syncplay_version }}
            ghcr.io/${{ vars.DOCKER_IMAGE }}:v${{ steps.get-version.outputs.syncplay_version }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
